### 1. Registrar usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "alonso33",
  "password": "Password123!"
}

### 2. Iniciar sesión (guarda el token de respuesta)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "alonso33",
  "password": "Password123!"
}

### 3. Ver perfil protegido con JWT
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhbG9uc28zMyIsImlhdCI6MTc4NjM4NzY2MSwiZXhwIjoxNzg2OTkyNDYxfQ.M1BqBnMi4L0DugnrfdPN8jPe-YQu-YtznjONAmrT0yc


### Obtener Clasificación de Pilotos
GET http://localhost:3000/api/drivers

### Obtener Clasificación de Equipos
GET http://localhost:3000/api/teams


